# Generated by Django 5.2.9 on 2025-12-22 17:38

import archives.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=191, unique=True, validators=[django.core.validators.RegexValidator('^[\\u0600-\\u06FF\\s]+$', 'يجب أن يحتوي الاسم بالعربي على حروف عربية ومسافات فقط.')], verbose_name='نوع المقالة')),
                ('name_en', models.CharField(blank=True, max_length=191, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', 'يجب أن يحتوي الاسم بالانجلزي  على حروف إنجليزية ومسافات فقط.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'نوع المقالة',
                'verbose_name_plural': 'أنواع المقالات',
            },
        ),
        migrations.CreateModel(
            name='AuthorityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=191, unique=True, verbose_name='نوع الجهة')),
                ('name_en', models.CharField(blank=True, max_length=191, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'نوع الجهة',
                'verbose_name_plural': 'انواع الجهة',
            },
        ),
        migrations.CreateModel(
            name='CareerStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=191, unique=True, verbose_name='المرحلة')),
                ('name_en', models.CharField(blank=True, max_length=191, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'المرحلة العملية',
                'verbose_name_plural': 'المراحل العملية',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=191, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'التصنيف',
                'verbose_name_plural': 'التصنيفات',
            },
        ),
        migrations.CreateModel(
            name='GeographicalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='الموقع')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('type', models.CharField(choices=[('محافظة', 'محافظة'), ('مديرية', 'مديرية'), ('مدينة', 'مدينة'), ('دولة', 'دولة')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'الموقع',
                'verbose_name_plural': 'المواقع الجغرافية',
            },
        ),
        migrations.CreateModel(
            name='PublicationMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=archives.models.publication_media_upload_path, verbose_name='ملف النشر')),
                ('original_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=191, verbose_name='اسم المنصة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
            ],
            options={
                'verbose_name': 'منصة نشر',
                'verbose_name_plural': 'منصات النشر',
            },
        ),
        migrations.CreateModel(
            name='PublicationPlatformType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=191, unique=True, verbose_name='نوع المنصة')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رمز المنصة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
            ],
            options={
                'verbose_name': 'نوع منصة النشر',
                'verbose_name_plural': 'أنواع منصات النشر',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='رقم المصدر')),
                ('file', models.FileField(blank=True, max_length=191, null=True, upload_to=archives.models.attachment_upload_path, verbose_name='الملف/المرفق')),
                ('original_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_url', models.BooleanField(default=False, verbose_name='مسار خارجي (رابط)')),
                ('can_be_shared', models.BooleanField(default=True, verbose_name='هل ممكن مشاركته')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أُنشى بواسطة')),
            ],
            options={
                'verbose_name': 'المرفق',
                'verbose_name_plural': 'المرفقات',
            },
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=191, unique=True, verbose_name='الجهة')),
                ('name_en', models.CharField(blank=True, max_length=191, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.authoritytype', verbose_name='نوع الجهة')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.geographicallocation', verbose_name='الموقع')),
            ],
            options={
                'verbose_name': 'الجهة',
                'verbose_name_plural': 'الجهات',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=191, verbose_name='عنوان المقال')),
                ('title_en', models.CharField(blank=True, max_length=191, null=True)),
                ('content', models.TextField(verbose_name='محتوى المقال')),
                ('article_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ المقالة')),
                ('language', models.CharField(choices=[('ar', 'عربي'), ('en', 'انجليزي')], default='ar', max_length=50, verbose_name='اللغة')),
                ('is_archived', models.BooleanField(blank=True, default=False, null=True, verbose_name='هل مؤرشف')),
                ('keywords', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='انشأت بواسطة')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.articletype', verbose_name='نوع المقال')),
                ('Authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.authority', verbose_name='الجهة/المؤسسة')),
                ('career_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.careerstage', verbose_name='المرحلة العلمية المرتبطة')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.category', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'المقالة',
                'verbose_name_plural': 'المقالات',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='رقم المصدر')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النشر')),
                ('page_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الصفحة')),
                ('issue_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='العدد للصحيفة')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='التاريخ للصحيفة')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='رابط الموقع')),
                ('book_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الكتاب')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='رابط الفيديو')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_publications', to='archives.publicationmedia', verbose_name='صورة الغلاف')),
                ('page_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_publications', to='archives.publicationmedia', verbose_name='صورة الصفحة')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.publicationplatform', verbose_name='منصة النشر')),
            ],
            options={
                'verbose_name': 'نشر',
                'verbose_name_plural': 'النشر',
            },
        ),
        migrations.AddField(
            model_name='publicationplatform',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.publicationplatformtype', verbose_name='نوع المنصة'),
        ),
        migrations.AddConstraint(
            model_name='publicationplatform',
            constraint=models.UniqueConstraint(fields=('name_ar', 'type'), name='unique_platform_name_per_type'),
        ),
    ]
