# Generated by Django 5.2.9 on 2025-12-22 18:46

import archives.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to=archives.models.publication_upload_path, verbose_name='صورة الغلاف'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='page_image',
            field=models.FileField(blank=True, null=True, upload_to=archives.models.publication_upload_path, verbose_name='صورة الصفحة'),
        ),
        migrations.AddField(
            model_name='publication',
            name='cover_image_original_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='page_image_original_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='PublicationMedia',
        ),
    ]
