# Generated by Django 5.2.8 on 2025-11-28 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=191)),
                ('name_en', models.CharField(blank=True, max_length=191, null=True)),
                ('type', models.CharField(choices=[('حكومي', 'حكومي'), ('خاص', 'خاص'), ('جمعية', 'جمعية')], default='حكومي', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareerStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=1000)),
                ('title_en', models.CharField(max_length=1000)),
                ('content', models.TextField()),
                ('publish_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('مسودة', 'مسودة'), ('معتمد', 'معتمد'), ('منشور', 'منشور'), ('ملغي', 'ملغي')], default='معتمد', max_length=20)),
                ('category', models.CharField(blank=True, choices=[('أخبار', 'أخبار'), ('بيانات', 'بيانات'), ('مقالات', 'مقالات'), ('رأي', 'رأي')], max_length=100, null=True)),
                ('language', models.CharField(choices=[('ar', 'عربي'), ('en', 'انجليزي')], default='ar', max_length=50)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(blank=True, null=True)),
                ('is_national', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('article_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.articletype')),
                ('Authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.authority')),
                ('career_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.careerstage')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archives.governorate')),
            ],
        ),
    ]
