# Generated by Django 5.2.8 on 2025-11-28 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_authority_careerstage_governorate_article'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=191, null=True)),
                ('file_original_name', models.CharField(blank=True, max_length=191, null=True)),
                ('source_table', models.CharField(blank=True, max_length=191, null=True)),
                ('source_type', models.CharField(blank=True, max_length=191, null=True)),
                ('source_id', models.BigIntegerField()),
                ('file_path', models.CharField(max_length=191)),
                ('file_extension', models.CharField(blank=True, max_length=191, null=True)),
                ('is_url', models.BooleanField(default=False)),
                ('can_be_shared', models.BooleanField(default=True)),
                ('file_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
