# Generated by Django 5.2.8 on 2025-11-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title_ar',
            field=models.CharField(max_length=191, unique=True),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='name_ar',
            field=models.CharField(max_length=191, unique=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_name',
            field=models.CharField(blank=True, max_length=191, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_original_name',
            field=models.CharField(blank=True, max_length=191, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='name_ar',
            field=models.CharField(max_length=191, unique=True),
        ),
        migrations.AlterField(
            model_name='careerstage',
            name='name_ar',
            field=models.CharField(max_length=191, unique=True),
        ),
    ]
