# Generated by Django 5.2.8 on 2025-11-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0004_alter_article_title_ar_alter_articletype_name_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='governorate',
            name='name',
        ),
        migrations.AddField(
            model_name='governorate',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='governorate',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
