# Generated by Django 5.2.8 on 2025-12-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0005_remove_governorate_name_governorate_name_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title_ar',
            field=models.CharField(max_length=191, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='name_en',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_extension',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_name',
            field=models.CharField(blank=True, max_length=191, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_original_name',
            field=models.CharField(blank=True, max_length=191, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_path',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='source_table',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='source_type',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='name_en',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='careerstage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careerstage',
            name='name_en',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
