# Generated by Django 5.2.9 on 2025-12-07 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0006_alter_article_title_ar_alter_article_title_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletype',
            options={'verbose_name': 'نوع المقالة', 'verbose_name_plural': 'أنواع المقالات'},
        ),
        migrations.AlterField(
            model_name='articletype',
            name='name_ar',
            field=models.CharField(max_length=191, unique=True, validators=[django.core.validators.RegexValidator('^[\\u0600-\\u06FF\\s]+$', 'يجب أن يحتوي الاسم بالعربي على حروف عربية ومسافات فقط.')], verbose_name='نوع المقالة'),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='name_en',
            field=models.CharField(blank=True, max_length=191, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', 'يجب أن يحتوي الاسم بالانجلزي  على حروف إنجليزية ومسافات فقط.')]),
        ),
    ]
