# Generated by Django 5.2.9 on 2025-12-07 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0007_alter_articletype_options_alter_articletype_name_ar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'المقالة', 'verbose_name_plural': 'المقالات'},
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'المرفق', 'verbose_name_plural': 'المرفقات'},
        ),
        migrations.AlterModelOptions(
            name='authority',
            options={'verbose_name': 'الجهة', 'verbose_name_plural': 'الجهات'},
        ),
        migrations.AlterModelOptions(
            name='careerstage',
            options={'verbose_name': 'مرحلة المهنة', 'verbose_name_plural': 'مراحل المهنة'},
        ),
        migrations.AlterModelOptions(
            name='governorate',
            options={'verbose_name': 'المحافظة', 'verbose_name_plural': 'المحافظات'},
        ),
        migrations.AlterField(
            model_name='article',
            name='Authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.authority', verbose_name='الجهة'),
        ),
        migrations.AlterField(
            model_name='article',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ـاريخ المصادقة'),
        ),
        migrations.AlterField(
            model_name='article',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المصادقة بواسطة'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.articletype', verbose_name='نوع المقال'),
        ),
        migrations.AlterField(
            model_name='article',
            name='career_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.careerstage', verbose_name='المهنة التي كان يشغلها'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('أخبار', 'أخبار'), ('بيانات', 'بيانات'), ('مقالات', 'مقالات'), ('رأي', 'رأي')], max_length=100, null=True, verbose_name='تصنيف المقال'),
        ),
        migrations.AlterField(
            model_name='article',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archives.governorate', verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='محتوى المقال'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_archived',
            field=models.BooleanField(blank=True, null=True, verbose_name='هل مؤرشف'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_national',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='مقال وطني'),
        ),
        migrations.AlterField(
            model_name='article',
            name='language',
            field=models.CharField(choices=[('ar', 'عربي'), ('en', 'انجليزي')], default='ar', max_length=50, verbose_name='اللغة'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(verbose_name='تاريخ النشر'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('مسودة', 'مسودة'), ('معتمد', 'معتمد'), ('منشور', 'منشور'), ('ملغي', 'ملغي')], default='معتمد', max_length=20, verbose_name='حالة المقال'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_ar',
            field=models.CharField(max_length=191, unique=True, verbose_name='عنوان المقال'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='can_be_shared',
            field=models.BooleanField(default=True, verbose_name='هل ممكن مشاركته'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أُنشى بواسطة'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_extension',
            field=models.CharField(blank=True, max_length=191, null=True, verbose_name='امتداد الملف'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_name',
            field=models.CharField(blank=True, max_length=191, null=True, unique=True, verbose_name='اسم الملف'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_original_name',
            field=models.CharField(blank=True, max_length=191, null=True, unique=True, verbose_name='اسم الملف الاصلي'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_path',
            field=models.CharField(max_length=191, verbose_name='مسار الملف'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_size',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='حجم الملف'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='is_url',
            field=models.BooleanField(default=False, verbose_name='مسار خارجي'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='source_id',
            field=models.BigIntegerField(verbose_name='رقم المصدر'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='source_table',
            field=models.CharField(blank=True, max_length=191, null=True, verbose_name='الجدول'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='source_type',
            field=models.CharField(blank=True, max_length=191, null=True, verbose_name='نوع المصدر'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل'),
        ),
        migrations.AlterField(
            model_name='authority',
            name='name_ar',
            field=models.CharField(max_length=191, unique=True, verbose_name='الجهة'),
        ),
        migrations.AlterField(
            model_name='careerstage',
            name='name_ar',
            field=models.CharField(max_length=191, unique=True, verbose_name='المهنة'),
        ),
        migrations.AlterField(
            model_name='governorate',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='المحافظة'),
        ),
    ]
