# Generated by Django 5.2.9 on 2025-12-08 10:05

import archives.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0008_alter_article_options_alter_attachment_options_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='file_extension',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='file_original_name',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='source_table',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='source_type',
        ),
        migrations.AddField(
            model_name='attachment',
            name='content_type',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='file',
            field=models.FileField(default=1, max_length=191, upload_to=archives.models.attachment_upload_path, verbose_name='الملف/المرفق'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='object_id',
            field=models.PositiveIntegerField(default=1, verbose_name='رقم المصدر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachment',
            name='is_url',
            field=models.BooleanField(default=False, verbose_name='مسار خارجي (رابط)'),
        ),
    ]
