# Generated by Django 5.2.9 on 2025-12-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0009_remove_attachment_file_extension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='original_name',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
