# Generated by Django 5.2.9 on 2025-12-08 18:00

import archives.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0010_attachment_original_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, max_length=191, null=True, upload_to=archives.models.attachment_upload_path, verbose_name='الملف/المرفق'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='original_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
