# Generated by Django 5.2.9 on 2025-12-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0011_alter_attachment_file_alter_attachment_original_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
