# Generated by Django 5.2.9 on 2025-12-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0012_alter_attachment_original_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title_ar',
            field=models.CharField(max_length=191, verbose_name='عنوان المقال'),
        ),
    ]
